apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bms
  name: bms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bms
    spec:
      containers:
      - image: fade2333/bms
        name: bms
        resources: {}
        ports: 
        - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: ${MYSQL_ROOT_PASSWORD}
      - image: mysql:8.0.29
        name: mysql
        resources: {}
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: db-scripts
            mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: db-scripts
          nfs:
            path: ${NFS_PATH}
            server: ${NFS_HOST}
status: {}