version: "3.9"
services:
  bms:
    image: fade2333/bms:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    links:
      - mysql
  mysql:
    image: mysql:8.0.29
    volumes:
      - db:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}