name: deploy bms
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -DskipTests=true clean package -f pom.xml
      - name: Build Docker Image
        run: docker build --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/bms:latest .
      - name: Docker Login
        run: docker login -u  ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bms:latest 
      - name: Stop the Previous Services
        uses: appleboy/ssh-action@v0.1.9
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          WORKER_DIR: ${{ secrets.WORKER_DIR }}
          NFS_HOST: ${{ secrets.NFS_HOST }}
          NFS_PATH: ${{ secrets.NFS_PATH }}
          BMS_CERT: ${{ secrets.BMS_CERT }}
          BMS_KEY: ${{ secrets.BMS_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          envs: MYSQL_ROOT_PASSWORD,WORKER_DIR,NFS_HOST,NFS_PATH,BMS_CERT,BMS_KEY
          script: |
            cd $WORKER_DIR
            if [ -f "k8s/deploy.yaml" ]; then envsubst < k8s/deploy.yaml | kubectl delete -f -; else echo "文件不存在，无需执行删除命令。"; fi
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "ci/k8s/deploy.yaml,scripts/db/bms.sql,ci/k8s/port-forward.sh"
          target: ${{ secrets.WORKER_DIR }}
          strip_components: 1
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.9
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          WORKER_DIR: ${{ secrets.WORKER_DIR }}
          NFS_HOST: ${{ secrets.NFS_HOST }}
          NFS_PATH: ${{ secrets.NFS_PATH }}
          PORT_FORWARD_HOST: ${{ secrets.PORT_FORWARD_HOST }}
          BMS_CERT: ${{ secrets.BMS_CERT }}
          BMS_KEY: ${{ secrets.BMS_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: MYSQL_ROOT_PASSWORD,WORKER_DIR,NFS_HOST,NFS_PATH,PORT_FORWARD_HOST,BMS_CERT,BMS_KEY
          script_stop: true
          script: |
            cd $WORKER_DIR
            if [ -f "save_pid.txt" ]; then if kill -9 `cat save_pid.txt` 2>/dev/null; then echo "进程已成功终止。"; else echo "进程不存在或无法终止。"; fi; else echo "文件不存在，无需执行删除命令。"; fi
            if [ -f "ingress_save_pid.txt" ]; then if kill -9 `cat ingress_save_pid.txt` 2>/dev/null; then echo "进程已成功终止。"; else echo "进程不存在或无法终止。"; fi; else echo "文件不存在，无需执行删除命令。"; fi
            envsubst < k8s/deploy.yaml | kubectl apply -f -
            chmod u+x k8s/port-forward.sh
            ./k8s/port-forward.sh
