name: deploy bms
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -DskipTests=true clean package -f pom.xml
      - name: Build Docker Image
        run: docker build --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/bms:latest .
      - name: Docker Login
        run: docker login -u  ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bms:latest 
      - name: Stop the Previous Services
        uses: appleboy/ssh-action@v0.1.9
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          WORKER_DIR: ${{ secrets.WORKER_DIR }}
          NFS_HOST: ${{ secrets.NFS_HOST }}
          NFS_PATH: ${{ secrets.NFS_PATH }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          envs: MYSQL_PASSWORD,WORKER_DIR,NFS_HOST,NFS_PATH
          script: |
            cd $WORKER_DIR
            if [ -f "k8s/deploy.yaml" ]; then envsubst < k8s/deploy.yaml | kubectl delete -f -; else echo "文件不存在，无需执行删除命令。"; fi
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "ci/k8s/deploy.yaml,scripts/db/bms.sql,ci/k8s/port-forward.sh,ci/k8s/kill-nohup.sh"
          target: ${{ secrets.WORKER_DIR }}
          strip_components: 1
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.9
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          WORKER_DIR: ${{ secrets.WORKER_DIR }}
          NFS_HOST: ${{ secrets.NFS_HOST }}
          NFS_PATH: ${{ secrets.NFS_PATH }}
          PORT_FORWARD_HOST: ${{ secrets.PORT_FORWARD_HOST }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: MYSQL_PASSWORD,WORKER_DIR,NFS_HOST,NFS_PATH,PORT_FORWARD_HOST
          script_stop: true
          script: |
            cd $WORKER_DIR
            export NFS_HOST=$NFS_HOST
            export NFS_PATH=$NFS_PATH
            export MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
            export PORT_FORWARD_HOST=$PORT_FORWARD_HOST
            chmod u+x k8s/kill-nohup.sh
            ./k8s/kill-nohup.sh "kubectl port-forward deployment/bms"
            envsubst < k8s/deploy.yaml | kubectl apply -f -
            chmod u+x k8s/port-forward.sh
            ./k8s/port-forward.sh
