name: deploy bms
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -DskipTests=true package
      - name: Move war to ci Directory
        run: mv target/bms.war ci/ && ls ci
      - name: Build Docker Image
        run: docker build --file ci/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/bms:latest .
      - name: Docker Login
        run: docker login -u  ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bms:latest